name: taxcalc-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
- "python>=3.12, <3.15"
- "numpy>=2.4"
- "pandas>=3.0"
- "bokeh>=3.7"
- "numba>=0.64"
- curl
- setuptools
- pytest
- pytest-cov
- pytest-xdist
- pytest-asyncio
- requests
- aiohttp
- pycodestyle
- pylint
- openpyxl
- pip
- pip:
    - "jupyter-book<2.0"
    - "paramtools>=0.20.0"
