#!/bin/bash
# (0) process command-line arguments
if [[ "$#" -ne 2 ]]; then
    echo "ERROR: number of command-line arguments not two"
    echo "USAGE: ./compare1 L YY"
    echo "       WHERE L is a letter that is valid make-in.tcl L input and"
    echo "             YY is valid make-in.tcl CALENDAR YEAR (20YY) input."
    exit 1
fi
L=$1
YY=$2
LYY=$L$YY
# (1) generate INPUT file in Internet-TAXSIM input format:
tclsh ../validation/make-in.tcl 20$YY $L > $LYY.in
# (2) convert INPUT file to a CSV-formatted INPUT file:
python ../../simtax.py --taxsim2441 --records $LYY.in
# (3) rename the CSV-formatted INPUT file:
mv $LYY.in.records $LYY.csv
# (4) use renamed CSV-formatted INPUT file as input to inctax.py script:
python ../../inctax.py $LYY.csv 20$YY
# (5) confirm no differences between inctax.py and simtax.py OUTPUT files:
diff $LYY-$YY.out-inctax $LYY.in.out-simtax
exit 0
