"""
Script that takes specified CSV-formatted input file, which is generated by
some Tax-Calculator script, and translates that file's variable names to be
appropriate variable names for TAXCALC SAS program input.
There are no changes in variable values, only variable names are changed.
"""
# CODING-STYLE CHECKS:
# pep8 --ignore=E402 in2sas.py
# pylint --disable=locally-disabled in2sas.py
# (when importing numpy, add "--extension-pkg-whitelist=numpy" pylint option)


import sys
import argparse
import re


def main(infilename, outfilename):
    """
    Contains high-level logic of the script.
    """
    # read contents of INPUT file
    with open(infilename, 'r') as infile:
        contents = infile.read()
    # translate from Tax-Calculator to TAXCALC SAS variable names
    contents = re.sub('e32800', 'e32700', contents, count=1)
    # write contents to OUTPUT file
    with open(outfilename, 'w') as outfile:
        outfile.write(contents)
    # return no-error exit code
    return 0
# end of main function code


if __name__ == '__main__':
    PARSER = argparse.ArgumentParser(
        prog='python in2sas.py',
        description=('Reads CSV-formatted INPUT file containing '
                     'Tax-Calulator input variable names and writes an '
                     'OUTPUT file with TAXCALC SAS input variable names. '
                     'There are no changes in variable values.'))
    PARSER.add_argument('INPUT',
                        help=('INPUT is name of required file that contains '
                              'CSV-formatted Tax-Calculator '
                              'input variable names.'))
    PARSER.add_argument('OUTPUT',
                        help=('OUTPUT is name of required file that contains '
                              'CSV-formatted TAXCALC SAS '
                              'input variable names.'))
    ARGS = PARSER.parse_args()
    sys.exit(main(ARGS.INPUT, ARGS.OUTPUT))
