#!/bin/bash
# Executes validation TESTS by calling TESTS scripts in various subdirectories.
# .... check number of command-line arguments
if [[ "$#" -gt 1 ]]; then
    echo "ERROR: can specify at most one command-line argument"
    echo "USAGE: ./tests [all]"
    echo "       (using the 'all' option may execute four tests at a time)"
    exit 1
fi
# .... specify whether or not to execute all tests
ALL=""
if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "all" ]]; then
        ALL="all"
    else
        echo "ERROR: optional command-line argument must be all"
        echo "USAGE: ./tests [all]"
        exit 1
    fi
fi
cd taxsim ; bash tests $ALL ; cd ..
exit 0
