#!/bin/bash
# Executes current-law & reform validation TESTS by calling test bash script.
# .... check number of command-line arguments
if [[ "$#" -gt 1 ]]; then
    echo "ERROR: can specify at most one command-line argument"
    echo "USAGE: ./tests [all]"
    echo "       (using the 'all' option may execute four tests at a time)"
    exit 1
fi
# .... specify whether or not to execute all tests
ALLTESTS=false
if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "all" ]]; then
        ALLTESTS=true
    else
        echo "ERROR: optional command-line argument must be all"
        echo "USAGE: ./tests [all]"
        exit 1
    fi
fi
# .... execute validation tests in parallel
echo "STARTING WITH VALIDATION TESTS : `date`"
if [[ "$ALLTESTS" == true ]] ; then
    printf "... starting test group 1 of 5 at `date`\r"
    bash test a13 . &
    bash test c13 18_0.07 &
    bash test c14 18_0.07 &
    wait
    printf "... starting test group 2 of 5 at `date`\r"
    bash test a14 . &
    bash test c13 19_0.05 &
    bash test c14 19_0.05 &
    wait
    printf "... starting test group 3 of 5 at `date`\r"
    bash test b13 . &
    bash test c13 50_1 &
    bash test c14 50_1 &
    wait
    printf "... starting test group 4 of 5 at `date`\r"
    bash test b14 . &
    bash test c13 75_500 &
    bash test c14 75_500 &
    wait
    printf "... starting test group 5 of 5 at `date`\r"
fi
bash test c13 . &
bash test c14 . &
wait
echo "FINISHED WITH VALIDATION TESTS : `date`"
echo "TEST RESULTS: any lines (starting with M) between the STARTING... and"
echo "              FINISHED... lines above indicate test failure caused by"
echo "              the actual *.taxdiffs results being different from the"
echo "              expected results; no M... lines implies tests passed."
exit 0
