#!/bin/bash
# Executes current-law validation TESTS by calling test bash script.
# .... check number of command-line arguments
if [[ "$#" -gt 1 ]]; then
    echo "ERROR: can specify at most one command-line argument"
    echo "USAGE: ./tests [all]"
    exit 1
fi
# .... specify whether or not to execute all tests
ALLTESTS=false
if [[ "$#" -eq 1 ]]; then
    if [[ "$1" == "all" ]]; then
        ALLTESTS=true
    else
        echo "ERROR: optional command-line argument must be all"
        echo "USAGE: ./tests [all]"
        exit 1
    fi
fi
# .... execute validation tests in parallel
echo "STARTING WITH CURLAW TESTS : `date`"
if [[ "$ALLTESTS" == true ]] ; then
    ./test a13 &
    ./test a14 &
    wait
    ./test b13 &
    ./test b14 &
    wait
fi
./test c13 &
./test c14 &
wait
echo "FINISHED WITH CURLAW TESTS : `date`"
echo "TEST RESULTS: any lines (starting with M) between the STARTING... and"
echo "              FINISHING... lines above indicate test failure caused by"
echo "              the actual ???.taxdiffs results being different from the"
echo "              expected results.  No M... lines implies tests passed."
exit 0
