package:
  name: taxcalc
  version: 0.0.0

build:
  entry_points:
    - tc = taxcalc.cli.tc:cli_tc_main

requirements:
  build:
    - "python>=3.11, <3.14"
    - "numpy>=1.26"
    - "pandas>=2.2"
    - "bokeh>=3.7"
    - "paramtools>=0.20.0"
    - numba
    - curl
    - openpyxl
    - behresp
    - "mcp[cli]"

  run:
    - "python>=3.11, <3.14"
    - "numpy>=1.26"
    - "pandas>=2.2"
    - "bokeh>=3.7"
    - "paramtools>=0.20.0"
    - numba
    - curl
    - openpyxl
    - behresp
    - "mcp[cli]"

test:
  commands:
    - which tc  # [unix]
    - where tc  # [win]
    - tc --help

about:
  home: https://github.com/PSLmodels/Tax-Calculator
