name: Build and Deploy Jupyter Book
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    if: github.repository == 'PSLmodels/Tax-Calculator'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: taxcalc-dev
          environment-file: environment.yml
          python-version: 3.12
          auto-activate: false

      - name: Build # Build Jupyter Book
        shell: bash -l {0}
        run: |
          pip install "jupyter-book<2"
          pip install -e .
          cd docs
          jb build .

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
